# Generated by Django 4.0.5 on 2022-08-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_favorites_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_data',
            field=models.JSONField(default=None, null=True),
        ),
    ]
