# Generated by Django 4.0.5 on 2022-08-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0003_serial_price_serial_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='serials/posters/'),
        ),
    ]
