# Generated by Django 4.0.5 on 2022-08-16 17:58

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='movies_movi_name_43dabd_gin'),
        ),
    ]
