# Generated by Django 4.0.5 on 2022-07-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_countries_movie_timing_movie_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='countries',
        ),
        migrations.AddField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(to='movies.countries'),
        ),
    ]
