# Generated by Django 4.0.5 on 2022-07-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='NoName', max_length=100)),
                ('last_name', models.CharField(default='NoName', max_length=100)),
                ('slug', models.SlugField(default='')),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='NoName', max_length=100)),
                ('last_name', models.CharField(default='NoName', max_length=100)),
                ('slug', models.SlugField(default='')),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movies.composer'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movies.director'),
        ),
    ]
