# Generated by Django 4.0.5 on 2022-07-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_actor_birthday_alter_movie_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='birthplace',
            field=models.CharField(default='No information', max_length=150),
        ),
        migrations.AlterField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(blank=True, default='', to='movies.countries'),
        ),
        migrations.AddField(
            model_name='actor',
            name='carrier_role',
            field=models.ManyToManyField(blank=True, default='No information', to='movies.carrierrole'),
        ),
    ]
