# Generated by Django 4.0.5 on 2022-07-31 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_carrierrole_actor_birthplace_alter_movie_countries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actors', to='movies.countries'),
        ),
    ]
