# Generated by Django 4.0.5 on 2022-08-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_actor_birthplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='time_of_action',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
