# Generated by Django 4.0.5 on 2022-08-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_time_of_action_alter_movie_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='time_of_action',
            new_name='action_time',
        ),
    ]
