# Generated by Django 4.0.5 on 2022-08-01 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_rename_time_of_action_movie_action_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='action_time',
            new_name='action',
        ),
        migrations.AddField(
            model_name='movie',
            name='yearseeess',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2030)]),
        ),
    ]
