# Generated by Django 4.0.5 on 2022-08-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_movie_options_movie_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/posters/'),
        ),
    ]
