# Generated by Django 4.0.5 on 2022-08-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_alter_comment_body_alter_comment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_ling',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
