# Generated by Django 4.0.5 on 2022-08-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_movie_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_poster',
            new_name='poster',
        ),
    ]
