# Generated by Django 4.0.5 on 2022-08-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.CharField(choices=[('M', 'Movie'), ('G', 'Game')], editable=False, max_length=1),
        ),
    ]
